openapi: '3.0.3'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1

paths:
  /test:
    get:
      responses:
        '200':
          description: OK
  /notify:
    post:
      description: notify tracker of resource found.
      requestBody:
        content:
          application/json:
            schema:
             $ref: '#/components/schemas/NotificationRequest'
      responses:
        '200':
          description: OK
  /resources/{resourceId}:
    get:
      description: retrieve information about single resource tracked by resmorph
      parameters:
        - name: resourceId
          in: path
          description: |-
            hash value of resource contents and location where the resource was found. The hash is computed
            as a Merkle tree of the sha256 hash of the resource contents and the location separately.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'


components:
  schemas:
    NotificationRequest:
      type: object
      properties:
        location:
          type: string
          format: URL
        reporter:
          type: string
        resource:
          type: string
          format: json
    Resource:
      type: object
      properties:
        resourceId:
          type: string
        location:
          type: string
          format: URL
        reporter:
          type: string
        resource:
          type: string
        match:
          type: string
        transformer:
          type: string
        transformation:
          type: string
          description: the transformation resultant from applying the transformer to the resource
        
      required:
        - resourceId
        - reporter
        - resource


  
